- name: Ansible Playbook with Check Diff for File
  hosts: localhost
  tasks:
    - name: Create a configuration file and check for differences
      template:
        src: config.j2
        dest: /etc/myapp/config.conf

