- name: Simple Ansible Playbook
  hosts: default
  tasks:
    - name: Print a message with local instance IP
      debug:
        msg: "Hello, this is a simple Ansible playbook for testing. Local instance IP is {{ ansible_default_ipv4.address }}"
