---
# - name: Print Message on EC2 Instance
#   hosts: ec2
#   become: true
#   gather_facts: true

#   tasks:
#     - name: Print a Message
#       command: echo "Hello from Ansible on EC2!"
- name: Print Message on EC2 Instance
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Print a Message and Intentionally Fail
      command: /path/to/nonexistent-command
      ignore_errors: no  # This line can be omitted as 'no' is the default value

