# - name: Print Message 
#   hosts: ec2
#   gather_facts: true

#   tasks:
#     - name: Print a Message
#       command: ls -la
- name: Print Message 
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Print a Message
      command: "echo 'Hello, This is a dummy message'"


